# Generated by Django 5.2.7 on 2025-10-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_editrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editrequest",
            name="requested_changes",
            field=models.JSONField(),
        ),
    ]
